# Model Notebook for Coding in SK-LEARN

In [341]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.linear_model import LinearRegression

In [342]:
# import the data
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [343]:
# seperate the features X and the target/label y
X = df[['total_bill']]
y = df['tip']
scaler = StandardScaler()
X = scaler.fit_transform(X)



In [344]:
# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)


In [345]:
# prepocess the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)




In [346]:
# build the model
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [347]:
y_pred = model.predict(X_test)

In [366]:
y_test



203    2.50
220    2.20
104    4.08
68     2.01
188    3.50
163    2.00
138    2.00
54     4.34
151    2.00
186    3.50
61     2.00
234    3.00
123    2.00
216    3.00
224    1.58
16     1.67
96     4.00
207    3.00
59     6.73
141    6.70
166    2.24
223    3.00
12     1.57
95     4.73
218    1.44
9      3.23
187    2.00
241    2.00
198    2.00
157    3.75
146    1.36
56     3.00
121    1.68
115    3.50
219    3.09
205    3.23
75     1.25
168    1.61
32     3.00
99     1.50
52     5.20
82     1.83
213    2.50
199    2.00
87     4.00
19     3.35
124    2.52
4      3.61
79     2.71
Name: tip, dtype: float64

In [357]:
y_pred


array([2.68421653, 2.23342263, 3.16477984, 3.09141951, 2.87027533,
       2.4088495 , 2.6416888 , 3.65810146, 2.33655236, 3.16265345,
       2.4088495 , 2.59171872, 2.63637283, 3.93346849, 2.36738496,
       2.03885828, 3.84097069, 5.05832686, 6.07261313, 4.58733228,
       3.14776874, 2.63956241, 2.5800236 , 5.21142667, 1.76349125,
       2.51197923, 4.17906611, 3.35083864, 2.32273085, 3.59856265,
       2.92237179, 4.98177695, 2.36738496, 2.7809671 , 4.14504393,
       2.69165888, 2.05799576, 2.0665013 , 2.54174864, 2.26531842,
       4.64155514, 2.01121526, 2.35143707, 2.3769537 , 2.88409684,
       3.13607362, 2.26744481, 3.55497173, 2.77884072])

In [350]:
model.predict([[20]])

array([21.87668358])

In [351]:
# evaluate the model
from sklearn.metrics import mean_squared_error, r2_score
print('MSE:',mean_squared_error(y_test,y_pred))
print('R2:',r2_score(y_test,y_pred))

MSE: 0.7561007994409374
R2: 0.5009421687014991


In [352]:
# save the model
import pickle
pickle.dump(model,open('./saved_models.pkl','wb'))


In [353]:
#load the model
import pickle
model_load = pickle.load(open('./saved_models.pkl','rb'))

In [354]:
model_load.predict([[130 ]])

array([125.47646888])