# Naive Based Algorithm

Naive Bayes is a family of generative machine learning algorithms used for classification tasks. It is based on Bayes' Theorem and assumes conditional independence of predictors. Despite this unrealistic assumption, Naive Bayes classifiers perform well, particularly with small sample sizes.

There are different types of Naive Bayes classifiers, including Gaussian, Multinomial, and Bernoulli, which differ based on the distributions of the feature values.

In Naive Bayes, the class-conditional probabilities and the prior probabilities are calculated to yield the posterior probabilities. The classifier then returns the class with the maximum posterior probability out of a group of classes for a given input.

To evaluate the performance of a Naive Bayes classifier, a confusion matrix can be plotted, which shows the actual and predicted values within a matrix.

Naive Bayes is commonly used in text classification, spam filtering, and recommendation systems. It is also used in other applications such as image classification and natural language processing.

Some advantages of Naive Bayes include its simplicity, scalability, and robustness to irrelevant features. However, it may perform poorly when the assumption of conditional independence is violated.

In summary, Naive Bayes is a powerful and versatile classification algorithm that is widely used in machine learning and data mining applications.

# Bayes Theorem
Bayes' Theorem is a fundamental concept in probability theory and statistics. It is named after the English mathematician Thomas Bayes. It is used to calculate the conditional probability of an event, given the probability of another event.

Bayes' Theorem states that the conditional probability of two events, A and B, is equal to the product of the probability of B given A, and the probability of A, divided by the probability of B. Mathematically, it can be represented as:

P(A|B) = P(B|A) * P(A) / P(B)

Here, P(A|B) is the probability of event A occurring, given that event B has occurred. P(B|A) is the probability of event B occurring, given that event A has occurred. P(A) and P(B) are the probabilities of events A and B, respectively.

Bayes' Theorem is used in various fields, including machine learning, statistics, and decision theory. It is the foundation of the Naive Bayes classifier, which is a popular algorithm used for classification tasks.

In machine learning, Bayes' Theorem is used to calculate the posterior probabilities of the classes given the input features. The classifier then selects the class with the highest posterior probability as the prediction.

In summary, Bayes' Theorem is a fundamental concept in probability theory and statistics that is used to calculate the conditional probability of two events. It is widely used in machine learning and other fields to make predictions and decisions based on data.






In [42]:
# import algorithm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import  GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.datasets import load_iris



In [43]:
# load the dataset

iris = load_iris()
X = iris.data
y = iris.target

In [44]:
# train test split the data

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [45]:
# model initialize
gnb = GaussianNB()

# train the model
gnb.fit(X_train, y_train)

# predict the test data
y_pred = gnb.predict(X_test)

# evaluate the model

print('accuracy_score',accuracy_score(y_test, y_pred))
print('confusion_matrix',confusion_matrix(y_pred,y_test))
print('classification_report',classification_report(y_pred,y_test))

accuracy_score 0.9777777777777777
confusion_matrix [[19  0  0]
 [ 0 12  0]
 [ 0  1 13]]
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      1.00      0.96        12
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [46]:
mnb = MultinomialNB()

# train the model
gnb.fit(X_train, y_train)

# predict the test data
y_pred = gnb.predict(X_test)

# evaluate the model

print('accuracy_score',accuracy_score(y_test, y_pred))
print('confusion_matrix',confusion_matrix(y_pred,y_test))
print('classification_report',classification_report(y_pred,y_test))

accuracy_score 0.9777777777777777
confusion_matrix [[19  0  0]
 [ 0 12  0]
 [ 0  1 13]]
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      1.00      0.96        12
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [47]:
bnb = BernoulliNB()

# train the model
gnb.fit(X_train, y_train)

# predict the test data
y_pred = gnb.predict(X_test)

# evaluate the model

print('accuracy_score',accuracy_score(y_test, y_pred))
print('confusion_matrix',confusion_matrix(y_pred,y_test))
print('classification_report',classification_report(y_pred,y_test))

accuracy_score 0.9777777777777777
confusion_matrix [[19  0  0]
 [ 0 12  0]
 [ 0  1 13]]
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      1.00      0.96        12
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45

